name: Adiatma Kamarudin
title: Adiatma Kamarudin
description: My personal blogs.
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: ''
google_analytics: '"UA-143014045-1"'
disqus: adiatma9024
include:
  - _pages
permalink: '/:title/'
authors:
  adiatma:
    name: Adiatma Kamarudin
    display_name: adiatma
    email: adiatma9024@gmail.com
    twitter: https://twitter.com/adiatma__
    description: "Software Engineer, Opensource Enthusiasm, and Father"
    web: "https://adiatma.github.io"
    gravatar: 4a2a99c8bd08b234fda70219c575c53a
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: 'disabled'
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: 'enabled'
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
jekyll_admin:
  hidden_links:
    - datafiles
